//
//  DetailInteractor.swift
//  Test
//
//  Created by Tana Chaijamorn on 17/8/2563 BE.
//  Copyright (c) 2563 BE Tana Chaijamorn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func doSetMap(request: Detail.SetMap.Request)
}

protocol DetailDataStore
{
  //var name: String { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  var presenter: DetailPresentationLogic?
  
  // MARK: Do setMap
  
  func doSetMap(request: Detail.SetMap.Request)
  {
    presenter?.presentSetMap(response: Detail.SetMap.Response(object: request.object))
  }
}
