//
//  ListWorker.swift
//  Test
//
//  Created by Tana Chaijamorn on 17/8/2563 BE.
//  Copyright (c) 2563 BE Tana Chaijamorn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListWorker {
    func doGetList(searchText: String) -> CitiesModel {
        return CoreDataWorker.searchCity(textSearch: searchText)
    }
}
