//
//  ListInteractor.swift
//  Test
//
//  Created by Tana Chaijamorn on 17/8/2563 BE.
//  Copyright (c) 2563 BE Tana Chaijamorn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBusinessLogic
{
  func doFetchList(request: List.fetchData.Request)
}

protocol ListDataStore
{
    
}

class ListInteractor: ListBusinessLogic, ListDataStore
{
  var presenter: ListPresentationLogic?
  var worker: ListWorker?
  
  // MARK: Do FetchList
  
  func doFetchList(request: List.fetchData.Request) {
    worker = ListWorker()
    let objects = worker?.doGetList(searchText: request.searchText)
    
    presenter?.presentFetchList(response: List.fetchData.Response(list: objects ?? []))
  }
}
