//
//  ListPresenter.swift
//  Test
//
//  Created by Tana Chaijamorn on 17/8/2563 BE.
//  Copyright (c) 2563 BE Tana Chaijamorn. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
  func presentFetchList(response: List.fetchData.Response)
}

class ListPresenter: ListPresentationLogic {
  weak var viewController: ListDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchList(response: List.fetchData.Response) {
    viewController?.displayFetchList(viewModel: List.fetchData.ViewModel(list: response.list))
  }
}
